### ISSUE TITLE
License is GPL3 but otherwise defined in `./backend/package.json`

### ISSUE THREAD

**Issue by ctmbl** [iScsc/iscsc.fr#32]
in `./backend/package.json` you can find:
```json
  "author": "Alexandre Tullot",
  "license": "ISC",
```
I think that @atxr deserves that author field but license isn't the right now that we've choose GPL3 or am I wrong?

**Comment by amtoine** [comment]
> license isn't the right now that we've choose GPL3 or am I wrong?
>
yup :+1: 
should be `LICENSE.MD`

**Comment by vSt11** [comment]
Hahaha i'm so stupid :')
So the license should be 'GPL3' right ?

**Comment by ctmbl** [comment]
@vSt11 maybe you wanted to comment on #50 but your not stupid really! 
this wasn't obvious and that's the whole point of the review process to arise these discussions and learn some knowledge :wink: 

As for your question I think we answered it on the PR #50 :+1:
