### ISSUE TITLE
improve the CLI of `gpg-share` with user, help and check flags

### ISSUE THREAD

**Issue by amtoine** [iScsc/iscsc.fr#37]
as introduced in #29, a new script has been added to the source to easily share the environment secrets with other developers using `pgp` keys and archives.

## the current script
the script is used as follows:
```bash
bash> ./scripts/gpg-share.sh <file-to-share> <user1> <user2> ...
```
or, when multi-words users have to be used or to save the list of people in a file
```bash
bash> USER_FILE="users.txt" ./scripts/gpg-share.sh <file-to-share>
```
with the following users
```txt
# users.txt
first user
another-one
last user
```
this is arguably not the best experience...

## idea of feature
during the review of #29, an idea has been introduced: **using flags**
- a `--user (-u)` flag to add one user from the standard input
- a `--users (-U)` flag to add additional users from a file

this will lead to the following usage:
```txt
# users.txt
additional user
```
```bash
bash> ./scripts/gpg-share.sh -u "first user" -u "user" -u "last one" -U users.txt
```
or 
```bash
bash> ./scripts/gpg-share.sh \
    -u "first user" \
    -u "user" \
    -u "last one" \
    -U users.txt
```
much better isn't it? :yum: 

we could also add `--help (-h)` to see the help of the script and why not `--check-keyring (-k)` to check to keyring of the user calling the script and make sure everything is ok :ok_hand:

**Comment by ctmbl** [comment]
I like every feature you proposed!
Maybe you could also address the problem of the script can't being run from `./scripts`? even if the current check is fine :+1: 

Just a slight proposal maybe:
```diff
- bash> ./scripts/gpg-share.sh -u "first user" -u "user" -u "last one" -U users.txt
+ bash> ./scripts/gpg-share.sh -u "first user" "user" "last one" -U users.txt
 ```
 ?

**Comment by amtoine** [comment]
> I like every feature you proposed!
>
coool :yum: 

> Maybe you could also address the problem of the script can't being run from `./scripts`? even if the current check is fine +1
> 
i might have a look into this, but will not be the primary focus of the PR :+1: 

> Just a slight proposal maybe:
> 
> ```diff
> - bash> ./scripts/gpg-share.sh -u "first user" -u "user" -u "last one" -U users.txt
> + bash> ./scripts/gpg-share.sh -u "first user" "user" "last one" -U users.txt
> ```
> 
> ?
>
yup
**what about allowing both?**
i'm just worried about `"first user" "user" "last one"` being treated by `bash` as `"first user user last one"` or `"first" "user" "user" "last" "one"` :thinking:

**Comment by amtoine** [comment]
> actually we'll see but at worst we'll forbid multi words username in command line parameters +1
>
perfect :ok_hand:
