### ISSUE TITLE
scripts are a bit all over the place

### ISSUE THREAD

**Issue by amtoine** [iScsc/iscsc.fr#38]
#20, #27 and #29 introduced some scripts to the source, `nginx/run_nginx.sh`, `bump.sh` and `scripts/gpg-share.sh` respectively

**i'm wondering if we could place them in a single location** :thinking: 

## proposition
i think `./scripts/` would be the best
`bump.sh` seems trivial to move from the root to `./scripts/`
i do not know if that's possible with `nginx/run_nginx.sh`, if not, that's ok :yum: 

## list the scripts
```bash
nushell> ls **/*.sh | get name
╭───┬──────────────────────╮
│ 0 │ bump.sh              │
│ 1 │ nginx/run_nginx.sh   │
│ 2 │ scripts/gpg-share.sh │
╰───┴──────────────────────╯
```

**Comment by ctmbl** [comment]
I don't know for `nginx` (@atxr will however) but I could do that with `bump.sh` after some light modifications :+1:

**Comment by amtoine** [comment]
> I don't know for `nginx` (@atxr will however)
>
no problem :yum: 

> but I could do that with `bump.sh` after some light modifications +1
>
that would be awesome :muscle:

**Comment by atxr** [comment]
Sorry to answer that late! But indeed `nginx` should stay in `/nginx`, this is just a little script run by docker during the deployment, and you should have to run it by yourself.
I totally agree for the two other scripts!

**Comment by ctmbl** [comment]
Then I'm right thinking that #56 will close this one!
