### ISSUE TITLE
Run Snyk to scan vulnerabilities

### ISSUE THREAD

**Issue by atxr** [iScsc/iscsc.fr#39]
When deploying the website, `docker` proposed me this:
```
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
```

We should probably give Snyk a try!  
[Here is the website](https://snyk.io/)

**Comment by ctmbl** [comment]
You're right I just added the right labels to this one and added it to the `v0.2.0` milestone!
