### ISSUE TITLE
Add new milestone for iScsc blog v0.0.2

### ISSUE THREAD

**Issue by atxr** [iScsc/iscsc.fr#4]
I want to propose the next milestone for the website, and I wanted to discuss about it before creating it.

Create a private space for authenticated users on the blog website to manage published articles.
New features:
- Personal space for each authenticated users
- Management of posts (add, remove, edit)
- Management of personal data (avatar, name, email, password)

Let me know what you think!

**Comment by amtoine** [comment]
this looks great to me :relieved: 

just one thing
you're talking about `v0.0.2` :thinking: 
is it a `git tag`? then a `v0.0.1` tag should be added right now or at the end of #2 as well!

**Comment by atxr** [comment]
> just one thing you're talking about `v0.0.2` thinking is it a `git tag`? then a `v0.0.1` tag should be added right now or at the end of #2 as well!
Yes of course the tag will be added at the end of #2

**Comment by ctmbl** [comment]
Looks great! I'll think about it and update this issue if I find anything to add :wink:

**Comment by amtoine** [comment]
@atxr 
do you want to open a PR yourself on this? :yum:

**Comment by ctmbl** [comment]
> do you want to open a PR yourself on this? 

If I understand this issue well the goal is to create a GitHub Milestone like I did for v0.0.1 nothing to do with PR and code I think!

**Comment by atxr** [comment]
Yes no PR at the moment, just project management :wink:

**Comment by atxr** [comment]
Milestone created!

**Comment by amtoine** [comment]
i do not get what milestone you are talking about :thinking: 
is it only a label on the issue? :thinking: 
i though you were talking about marking the commit tree with tags but **there is no tag on this repo** for now :confused: 

also **why did you close this issue?**
you created a milestone but your 3 main points, i.e.
- Personal space for each authenticated users
- Management of posts (add, remove, edit)
- Management of personal data (avatar, name, email, password)

have not been adressed yet :thinking:

**Comment by amtoine** [comment]
i'm discovering that "milestone" feature :open_mouth:

**Comment by atxr** [comment]
Ok! I think (if I get it well) that a milestone is some kind of goal to reach. You can

**Comment by ctmbl** [comment]
> You can assign PR, issues and features to a milestone, and when the milestone is completed, you can add the corresponding tag. Is it more clear?

that's absolutely how I see it!
