### ISSUE TITLE
The title of the webpage is still "React App"

### ISSUE THREAD

**Issue by atxr** [iScsc/iscsc.fr#40]
The title and the icon of the iscsc.fr website, shown in the tab of your browser, are still the default ones.

**Comment by amtoine** [comment]
i was about to open the same :wink:

**Comment by amtoine** [comment]
the same issue appears in a discord preview of the link to the blog, but that should be the same :+1:

**Comment by loki1205** [comment]
Hi, I am Loknath Kumar Mishra. I would like to contribute. Kindly assign this to me and let me know what should be displayed instead of "React App"

**Comment by ctmbl** [comment]
@loki1205 
> Hi, I am Loknath Kumar Mishra. I would like to contribute. Kindly assign this to me and let me know what should be displayed instead of "React App"

Sorry a PR has already been opened solving this Issue, this is our fault for not explicitly assigning the person to the Issue, again sorry for that :confused: 
However there are other [good first issues](https://github.com/iScsc/iscsc.fr/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) and we would greatly appreciate your contribution!!
Thanks a lot for your interest for our project!
