### ISSUE TITLE
Add node and npm version

### ISSUE THREAD

**Issue by atxr** [iScsc/iscsc.fr#46]
Currently, the documentation doesn't mention the `node` and `npm` version used.
We should add the following information in the repo:
- `node 19`
- `npm 8.19.2`

**Comment by amtoine** [comment]
the question is:
- the `README`
- the `package.json`
- the wiki
- a combination of these three

? :yum:

**Comment by atxr** [comment]
The `README` will be enough!

**Comment by amtoine** [comment]
> The `README` will be enough!
>
sensible :ok_hand:
