### ISSUE TITLE
Add link to GitHub repo on the home page

### ISSUE THREAD

**Issue by ctmbl** [iScsc/iscsc.fr#55]
I'd like to see the GitHub logo with a link to the repo right next to the iScsc title on the home (currently `/blog`) page
![iscsc wbesite](https://user-images.githubusercontent.com/79016298/206060287-cd292244-0719-4d66-a55f-10a426f26674.png)

This should be quite simple as it is only frontend side, I'll then assign the `good first issue` label :+1: 
Tell me what you think of the idea!

**Comment by amtoine** [comment]
i personnally think it's a great idea :+1: 

maybe not next to the title, but in a footer?

**Comment by ctmbl** [comment]
Yep that would be good too, I'll see if I can work on either these to have an imagery :+1:

**Comment by amtoine** [comment]
> Yep that would be good too, I'll see if I can work on either these to have an imagery +1
>
looking forward to it :+1:

**Comment by Sheikh-JamirAlam** [comment]
@ctmbl Added the github logo which is linked to the github repo. If you like it I can make a pr. Please let me know.
![image](https://user-images.githubusercontent.com/48979376/206473282-c078ee4a-1d2e-412b-8fe4-209a524cf1b0.png)

**Comment by ctmbl** [comment]
@Sheikh-JamirAlam 
I'd really like to see it! Additionally, do you think you can provide an imagery with the logo in a footer as suggested by @amtoine, but sure according to me this looks great!
Thanks for contributing!

**Comment by Sheikh-JamirAlam** [comment]
@ctmbl @amtoine How does this look? I will need the links you want to add in the footer section.
![image](https://user-images.githubusercontent.com/48979376/206558874-21bdce61-88df-4c46-b042-0084e3787a6e.png)

**Comment by ctmbl** [comment]
> How does this look? I will need the links you want to add in the footer section.

Actually it looks good! But I don't think we need so much for now, not enough stuff to put there. what do you think @amtoine ?

**Comment by Sheikh-JamirAlam** [comment]
Thanks for the feedback✨
