### ISSUE TITLE
Add containerization in development mode

### ISSUE THREAD

**Issue by ctmbl** [iScsc/iscsc.fr#64]
#20 added containerization to deploy the website in production mode. 

I would like to extend it to development mode in order to:
 - not mess with the host (developer)'s environment
 - solve env issues for Windows developer
 - homogenize modes
 - create a single script to run either development or production mode, transparently for the user 
 - solve potential version/environment problem for developer working on different machines
 
 Would be nice to have feedback on this!

 *I'm currently working on so I'm assigning it to myself*

**Comment by amtoine** [comment]
> * not mess with the host (developer)'s environment
> * solve env issues for Windows developer
> * homogenize modes
> * create a single script to run either development or production mode, transparently for the user
> * solve potential version/environment problem for developer working on different machines
> 
looks great :ok_hand: 

> _I'm currently working on so I'm assigning it to myself_
>
a preview of what you would like to do? :yum: 
i feel this would require enhancing the `Dockerfile`s, right? :thinking:

**Comment by ctmbl** [comment]
@amtoine 
> a preview of what you would like to do? yum

I see it that way: currently to start in dev mode you must open 2 terminals and run the needed commands in the `./backend` folder first, then `./frontend`. 
The two process communicate together via the opened ports (defined in the `.env.development`) and the frontend calls the backend endpoints (`/api/*`) prepending the URL defined in the `./frontend/package.json` : 
```json
{"proxy": "http://localhost:3001"}
```
 @atxr will correct me if I'm wrong

Now I want to put these two independent services in two containers, as done in production mode but to communicate together `localhost` won't do. 
I have some solutions:
 - change the proxy to `http://<backend container>:<port>` (like [here](https://stackoverflow.com/a/50207462)) which I'd like to avoid --> starting dev mode without docker won't work anymore
 - define the proxy in the code, making it depending of an an env var --> didn't try it but I [saw this post](https://stackoverflow.com/a/70413065)
 - use an `nginx` container without HTTPS as done in prod mode --> will require another nginx conf
 
Don't know what's the best solution so I'm listening to your opinion. 
Currently it's the only hard change needed I identified, another one is the `start` script in the same file but it's easily solvable.
 
>  i feel this would require enhancing the Dockerfiles, right?

No a different one instead!

**Comment by amtoine** [comment]
@ctmbl
thanks for the reply :yum: 

it's a bit technical for me right now :confused: 
i did not follow everything about `docker` here :eyes: 

i do not really get the difference between the "production" `docker` we have now and this new "development" one :thinking: 
ok, the "development" should refresh itself when changes are made to the source locally, but i think that's all i understood :open_mouth:

**Comment by ctmbl** [comment]
@amtoine 
> i do not really get the difference between the "production" docker we have now and this new "development" one thinking

Actually I must confess that for now there is not much differences, but enough to make two different files.
 - the dev one should not "refresh itself" it should share a volume, that means the image doesn't actually embed the code!
 - the build one embeds the code but a "built" version of it: the frontend part is built if I did understood what @atxr explain me once
 - with and without `docker` the communication between front and backend is different
 - in dev mode we do not use HTTPS certificates, it does bring a difference in the docker-compose file

**Comment by amtoine** [comment]
okok thanks for the details :ok_hand: 

## an idea
if the two images, the production and the development, share the same structure, e.g. the same base image, some `npm` commands, ..., you can put them inside a single `Dockerfile` and call one or the other with `docker build --target <target>`
see [Multiple images, one Dockerfile](https://stackoverflow.com/questions/49754286/multiple-images-one-dockerfile) :+1: 

that should simplify the file structure of the repo a bit :relieved:

**Comment by atxr** [comment]
> okok thanks for the details ok_hand
> ## an idea
> 
> if the two images, the production and the development, share the same structure, e.g. the same base image, some `npm` commands, ..., you can put them inside a single `Dockerfile` and call one or the other with `docker build --target <target>` see [Multiple images, one Dockerfile](https://stackoverflow.com/questions/49754286/multiple-images-one-dockerfile) +1
> 
> that should simplify the file structure of the repo a bit relieved

Yes sure that's how I imagine it!

**Comment by ctmbl** [comment]
@atxr @amtoine 

I just retried something for this issue, after having set it out for a few months.

About the previous problems we had:

### Multiple `Dockerfile` or one to rule them all
I created two `Dockerfile` named `Dockerfile` and `Dockerfile.dev` I'll PR it as it and you'll request a change while reviewing if you want to stand your ground :+1: 

### About `npm install`
Actually I was wrong and thus @atxr understood me wrong, let's clarify it (and **there is no problem anymore**)

I worried that installing in the image build would require rebuilding after changing the dependencies, **and that's the case** but **it isn't an issue**, when adding a new or removing an old dependency, we already have to re run the website, so this won't be so annoying to stop and restart the container **ONLY IN THE CASE of dependencies changes**

> Ofc we won't need to restart the container for each code changes bevaue I shared a volume in the docker compose :+1: 

### About `nodes_modules`
`yarn` seems OK but I don't want to change it right now, having the node_modules embedded in the imlage is not such a problem in the end and let the possibility for the suer to run the website from outside the container (the node_modules won't overlay each other :+1:
