### ISSUE TITLE
Add error message in the main blog page if `deleteArticle` fails

### ISSUE THREAD

**Issue by atxr** [iScsc/iscsc.fr#8]
No else here?

_Originally posted by @ctmbl in https://github.com/iScsc/iscsc.fr/pull/2#discussion_r979150269_

**Comment by amtoine** [comment]
nice :ok_hand:

**Comment by ctmbl** [comment]
I think there is more information to come :laughing:

**Comment by atxr** [comment]
I fixed this with a "quick dirty fix" in [6066c2c](https://github.com/atxr/iscsc.fr/commit/6066c2c857cf4bf7fdd23da864a5dcc8690317df)
I just send an alert and I will think later to a better way, maybe some kind of notifications
